development:
  adapter: mysql2
  encoding: utf8
  database: fetaro_mjt_dev
  username: fetaro
  password: fetaro
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: fetaro_mjt_pro
  username: fetaro
  password: fetaro
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: fetaro_mjt_test
  username: fetaro
  password: fetaro
  socket: /var/lib/mysql/mysql.sock
