development:
  adapter: mysql2
  encoding: utf8
  database: mj_tsumotter_dev
  username: root
  password: 
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: mj_tsumotter_pro
  database: msuke_pro
  username: root
  password: 
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: mj_tsumotter_test
  username: root
  password: 
  socket: /opt/local/var/run/mysql5/mysqld.sock
